name: Build and Deploy to TestFlight
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy to TestFlight
        run: |
          npm install -g eas-cli
          eas login -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APP_SPECIFIC_PASSWORD }}
          eas build -p ios --profile distribution

      - name: Upload to TestFlight
        uses: wzieba/TestflightUploader@v1.0.0
        with:
          api-token: ${{ secrets.TESTFLIGHT_API_TOKEN }}
          ipa-path: './ios/build/outputs/ipa/boilerplate.ipa'
          notify: true
          teams: 'Testflight Testers'
